[package]
name = "xrunits"
version = "0.1.1"
authors = ["xstater <a166224@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
